### ISSUE TITLE
Save processing as a "template" for source?

### ISSUE THREAD

**Issue by robgazy** [stemrollerapp/stemroller#15]
Once a file is processed, are there parameters generated that could be saved for future use, or do I always have to re-process the file from scratch? 
An example use case might be if I lost the output wav files, could I load a template saved by a previous run on the same file to more quickly extract the result?

**Comment by iffyloop** [comment]
Sorry, I don't exactly understand what you mean by a "template", but the output `wav` files are the only output of Demucs so I don't think this is possible. Feel free to clarify if I misunderstood. FYI, StemRoller bundles pretrained models for use with Demucs, which are then used to compute the output stems, so that might be sort of like what you're describing? It definitely doesn't retrain the entire AI model every time you split a file (that would probably take days on a regular PC).

**Comment by iffyloop** [comment]
Closing for now as the issue doesn't completely make sense. Let me know if I need to re-open it or if you need anything else!

**Comment by robgazy** [comment]
Sorry for the weird question, and thanks for the answer. 
I'm just thinking if a file has already been processed once is there a way to process faster the second time: the first run draws the map but subsequent runs just follow the map.  
I'm imagining the "processing" as two phases: a calculation/algorithm phase that analyzes the source and generates solutions to variables, followed by a cutting/demuxing phase that applies those derivates and produces the wav files. 
I'm getting the feeling this may not be how this type of processing works: maybe there is not two phases at all.
Thanks again!
