### ISSUE TITLE
Import our own files?

### ISSUE THREAD

**Issue by irish-moss** [stemrollerapp/stemroller#23]
Will there be an option to drag in our own files in the future versus internet search? 
I really love the app and am blown away how much better it is than spleeter based apps. The quality is remarkable. 
It's found anything I searched in seconds. 
Thanks
Rob

**Comment by iffyloop** [comment]
This is implemented already in the most recent version of StemRoller. Just drag-and-drop a file onto the window, or click the "select a local file" link that appears when the search bar is empty. I'm closing this issue for now since the feature already exists, but if you experience any problems then I'm happy to reopen it.
