### ISSUE TITLE
Process takes time forever with Mac1

### ISSUE THREAD

**Issue by ethyaan** [stemrollerapp/stemroller#28]
Hey,
I've tried it few time and I understood that same file which I successfully extracted vocals from in windows with Intel CPU,
Same thing is not working with M1 CPU and neither any other thing that I search and I try.
it will be in process like 20 hours something and nothing happens.
Using apple M1 chip.

**Comment by itsethanr** [comment]
Well, Finally I managed to make it work but only with wav file, still didn't work with mp3 but worked perfectly fine with wav file

**Comment by iffyloop** [comment]
Sorry for the late reply. I'm glad it worked with WAV; that's strange that it froze when using MP3. It should work, but if it doesn't then you should see a message that says "Failed" rather than the app hanging with the "Processing" status. Not sure how much I can do to troubleshoot this at the moment, but did you happen to try running with from the Terminal at any point? If so, could you paste the output here (of course, feel free to redact usernames/filenames/etc).

**Comment by iffyloop** [comment]
Closing this issue for now since I haven't heard back in a while and I don't have an M1 Mac to test. Feel free to provide more information and we can reopen if necessary.
