### ISSUE TITLE
Suggestion need support for multiple files from local stored files and support for AMD Gpus

### ISSUE THREAD

**Issue by DJboutit** [stemrollerapp/stemroller#37]
Two suggestion 

Needs to support multiple files like a max of 18 to 25 files in one go from local stored files

Needs support for AMD GPUs AMD GPUs are 20% to 45% cheaper than same NVidia GPU that = to a AMD more people will be switching to AMD GPUs in the next few years.

**Comment by iffyloop** [comment]
You can queue up multiple tracks while one is already processing, just keep searching for the next songs you want and click Split. AMD GPU support is not available because Demucs GPU acceleration uses CUDA, which is proprietary to NVIDIA. Will close this issue for now since neither of those requests are currently actionable, but feel free to ask any further questions in the Discord chat.
