### ISSUE TITLE
Request: isolate guitars, synths and piano 

### ISSUE THREAD

**Issue by jorgeauh** [stemrollerapp/stemroller#42]
Thanks for sharing this amazing project, only for curiosity 
Is it possible that we can get the isolation of guitars, synths and pianos individually instead of get mixed in a single audio file?
Thank you in advanced

**Comment by iffyloop** [comment]
IIRC there is a 6-stem model with support for piano and guitar which you can access if you run the Demucs CLI directly instead of using StemRoller: https://github.com/facebookresearch/demucs
Unfortunately this model isn't included with StemRoller, and won't be until I'm able to implement model download/management within StemRoller (so people can change which model is used for splitting). Also, the documentation states that piano extraction does not usually work well...
I don't think Demucs comes with pre-trained models for synths unfortunately, so can't help you there.
