### ISSUE TITLE
Possible to separate guitar and piano?

### ISSUE THREAD

**Issue by Zacharybinx34** [stemrollerapp/stemroller#54]
This program is great, but is it possible to separate guitar and piano?

**Comment by iffyloop** [comment]
Not currently, but this may be added in a future version. If you're comfortable with using the CLI, you can use Demucs directly instead of through the StemRoller GUI: https://github.com/facebookresearch/demucs (use the `htdemucs_6s` model)

**Comment by Zacharybinx34** [comment]
What is the CLI? Basically, what version of this AI software is the most advanced atm?

**Comment by iffyloop** [comment]
The CLI is short for "command-line interface", where you type commands into Terminal/Command Prompt instead of a point-and-click desktop graphical UI.  This is the default way Demucs works - if you visit the link I shared above (https://github.com/facebookresearch/demucs) you should find instructions on how to set it up. I'm closing this issue for now, as implementing a model downloader (for the 6 stems model) in StemRoller would be non-trivial and I'm concerned that the additional download size + splitting time is not worth it to make the 6 stems model default, but ideally this feature would exist in a successor to StemRoller at some point.
