### ISSUE TITLE
Anti-Virus-Tools show potential thread for demucx-cxfreeze.exe

### ISSUE THREAD

**Issue by jholzer** [stemrollerapp/stemroller#63]
Hi!

In download for version 2.0.6-win-cuda Bitdefender shows a potential thread:
(only german screenshot, sorry for this...)

![image](https://github.com/stemrollerapp/stemroller/assets/15092942/d5853b4e-08e2-4356-8ea6-becbd26ebc5f)

Also "Virustotal" is bringin some warnings:

![image](https://github.com/stemrollerapp/stemroller/assets/15092942/555e3908-902b-4595-b85a-33ba871341a5)

**Comment by iffyloop** [comment]
@jholzer those are most likely false positives due to `demucs-cxfreeze`'s use of PyInstaller, assuming you downloaded StemRoller from the official website https://stemroller.com or this GitHub page. I don't think there's much I can do about this, but feel free to re-open the issue if you have a suggestion.
