### ISSUE TITLE
Ability to split Rhythm and Lead guitar

### ISSUE THREAD

**Issue by twhippp** [stemrollerapp/stemroller#76]
I'm using this tool to make charts for rhythm games and when a solo happens, all guitars get muted if a note is missed. It'd be nice to split the rhythm and lead guitar so rhythm will still play during the solo.

**Comment by iffyloop** [comment]
This is a great idea, and one that has been requested before. Unfortunately, my current knowledge of machine learning is insufficient to implement this - StemRoller is just a wrapper around the Demucs tool, which does not have a model for separation rhythm/lead guitar (and that would probably require a different type of model than source separation, since the different between rhythm/lead guitar is more nuanced than e.g. guitar and drums). Closing as not planned, but thanks for the suggestion, and feel free to reply again if you have the skills to implement this or other relevant information.
