### ISSUE TITLE
Suggestion: Show progress instead of "Processing"

### ISSUE THREAD

**Issue by alectrocute** [stemrollerapp/stemroller#8]
Since this is a long-running process, it would be really helpful to print some sort of progress/stdout/etc. to the user. I'd be happy to make a PR for this if I have time, but am leaving this here just in case.

**Comment by iffyloop** [comment]
Great idea! Should be possible, as Demucs prints progress during processing files, just need to figure out a way to handle that stdout data...

**Comment by iffyloop** [comment]
After a short while attempting to parse data from the Demucs process and update the UI accordingly, it turns out this is a non-trivial issue that will require some refactoring (and also better understanding of how to stream the data from the Demucs child process). Would really like to have this feature implemented but am not planning to work on it myself anytime in the near future. Will leave the issue open though in case anyone else wants to give it a try or I have time to fix it later.

**Comment by iffyloop** [comment]
Devin Burnette's changes have been merged into the `develop` branch and should be merged into `main` shortly... closing.
